In [2]:
import pandas as pd
from pathlib import Path

In [3]:
RAW = Path('../data/raw')

In [4]:
selic = pd.read_csv(RAW / 'selic.csv', sep=';', decimal=',')
selic.head()

         data  valor
0  01/01/2015   0.94
1  01/02/2015   0.82
2  01/03/2015   1.04
3  01/04/2015   0.95
4  01/05/2015   0.99

In [5]:
selic.dtypes

data         str
valor    float64
dtype: object

In [6]:
ipca = pd.read_csv(RAW / 'ipca.csv', sep=';', decimal=',')
ipca.head()

         data  valor
0  01/01/2015   1.24
1  01/02/2015   1.22
2  01/03/2015   1.32
3  01/04/2015   0.71
4  01/05/2015   0.74

In [7]:
ipca.dtypes

data         str
valor    float64
dtype: object

In [8]:
selic = selic.rename(columns={
    "valor": "selic"
})

In [9]:
selic.head()

         data  selic
0  01/01/2015   0.94
1  01/02/2015   0.82
2  01/03/2015   1.04
3  01/04/2015   0.95
4  01/05/2015   0.99

In [10]:
ipca = ipca.rename(columns={
    "valor":"ipca"
})

In [11]:
ipca.head()

         data  ipca
0  01/01/2015  1.24
1  01/02/2015  1.22
2  01/03/2015  1.32
3  01/04/2015  0.71
4  01/05/2015  0.74

In [12]:
selic['data'] = pd.to_datetime(selic['data'], format='%d/%m/%Y')

In [13]:
selic.head()

        data  selic
0 2015-01-01   0.94
1 2015-02-01   0.82
2 2015-03-01   1.04
3 2015-04-01   0.95
4 2015-05-01   0.99

In [14]:
ipca['data'] = pd.to_datetime(ipca['data'], format='%d/%m/%Y')

In [15]:
ipca.head()

        data  ipca
0 2015-01-01  1.24
1 2015-02-01  1.22
2 2015-03-01  1.32
3 2015-04-01  0.71
4 2015-05-01  0.74

In [16]:
selic_ipca_comparative = selic.merge(
    right=ipca,
    on= 'data',
    how='inner')

In [18]:
print(selic_ipca_comparative.shape)
print(selic_ipca_comparative.isna().sum())

(120, 3)
data     0
selic    0
ipca     0
dtype: int64